[package]
name = "rs-music-client"
version = "0.1.0"
authors = ["STSchiff <chrisheib@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.13" # audio player
#chrono = "0.4"
iced = {version = "0.2", features = ["canvas", "tokio"]} # gui
reqwest = {version = "0.11", features = ["blocking"]} # download
anyhow = "1"
#futures = "0.3" # async
#tokio = { version = "1", features = ["full"] } # async